Stage-VI-1: some code refactored
4meech/LearnWordsTGBot pull request #3
Opened 2024-06-11 17:07 UTC by 4meech

Что-то я застрял. Варианты ответов не меняются, уже сам не могу разобраться как я реализовал логику проверки верного индекса ответа чтобы перетащить её в отдельный метод. Нужна помощь и пинок в верном направлении :)

2024-06-12 13:24 UTC, danelyan requested changes
Ты был очень близок ))
Просто обрати внимание, что получение Question у тебя находится **за циклом** изучения слов.

2024-06-12 13:24 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +//    val possibleAnswers: List<Word>,
это не нужный коммент

2024-06-12 13:24 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +        val learnedWords = dictionary.filter { it.correctAnswersCount >= ANSWERS_TO_LEARN }.size
ANSWERS_TO_LEARN и VARIANTS_OF_ANSWERS давай теперь сделаем полями класса LearnWordsTrainer и вынесем в основной конструктор

2024-06-12 13:24 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +//            possibleAnswers = possibleAnswers,
можно удалить

2024-06-12 13:24 UTC, danelyan commented on src/main/kotlin/Main.kt
> +                while (userAnswer != "0") {
тут лучше `while(true)`, а выходить ниже через if

2024-06-12 13:24 UTC, danelyan commented on src/main/kotlin/Main.kt
> +
вот тут, как только получаешь значение: `if( userAnswer == "0") break;`

2024-06-12 13:24 UTC, danelyan commented on src/main/kotlin/Main.kt
> +                var question = trainer.getNextQuestion()
Получается что ты получаешь Question только один раз, при входе в изучение слов. Надо внутри while перенести

2024-06-12 13:24 UTC, danelyan commented on src/main/kotlin/Main.kt
> +                        if (variant == question?.correctAnswer) correctIndex = index + 1
тут он не должен быть нулябельным (убери ?)

2024-06-13 18:31 UTC, 4meech commented
Какие-то вещи получились в процессе случайно, откровенно говоря. Зачем-то решил переделать определения правильного ответа -> через обращение к индексу. Работает, скорее, вопреки, а не благодаря, до сих пор не пойму как именно :) Но идиотом себя уже чувствую меньше.

2024-06-13 18:33 UTC, 4meech commented
Ну, вот что-то такое я выстрадал :)

2024-06-16 07:43 UTC, danelyan approved these changes
Вроде бы все круто!

2024-06-16 09:40 UTC, merged