Stage IX
4meech/LearnWordsTGBot pull request #6
Opened 2024-06-27 10:50 UTC by 4meech

Застрял. Смог добиться только вывода статистики и сообщения "вы выучили все слова", если не осталось невыученных слов. Я уже перестаю понимать что я делаю :) Нужна помощь

2024-06-28 05:53 UTC, danelyan requested changes

2024-06-28 05:53 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +//        if (text != null && chatId != null) {
Закоменченный код не должен попадать в master, если только он что-то не объясняет (пример использования или типо того)

2024-06-28 05:53 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        if (text == "/start" && chatId != null) {
Обрати внимание, тут и ниже ты в каждом if проверяешь chatId на null.
То есть, если chatId - то итерацию цикла вообще можно не продолжать:
```
val chatId = chatIdRegex.find(updates)?.groups?.get(1)?.value ?: continue
```

2024-06-28 05:53 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +//            val questionBody = question.asConsoleString()
закоменченный код

2024-06-29 17:28 UTC, 4meech commented
Ну, в общем-то яснее со времени первого ПР по этому этапу мне так не стало. Бот обрабатывает нажатия ответов, но неверно их учитывает. Я не могу сообразить как передать текущий объект question на проверку

2024-06-29 18:38 UTC, 4meech commented
Не придумал ничего лучше, чем создать internal поле currentQuestion

2024-07-01 04:21 UTC, danelyan requested changes

2024-07-01 04:21 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        if (text == "/start") {
Попробуй тут вместо набора if использовать when.
В idea есть даже такой экшен.
Правой кнопкой на if:
<img width="300" alt="Screenshot 2024-07-01 at 07 17 00" src="https://github.com/4meech/LearnWordsTGBot/assets/7125622/15e4ae5d-c0e5-4959-a49b-65c52b646bda">

Далее `Show Context Action` → `Replace if with when`:
<img width="300" alt="Screenshot 2024-07-01 at 07 17 09" src="https://github.com/4meech/LearnWordsTGBot/assets/7125622/9f87c5f9-9e68-49a4-9fb1-1583adb5d35c">

2024-07-01 04:21 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        } else if (data == "exitToMainMenu") {
Нужно вынести в константу

2024-07-01 04:21 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +        currentQuestion = Question(
> Не придумал ничего лучше, чем создать internal поле currentQuestion

И это корректное решение. Еще можно не передавать в `checkAnswer()`, а использовать currentQuestion

2024-07-01 09:31 UTC, 4meech commented on src/main/kotlin/LearnWordsTrainer.kt
> +        currentQuestion = Question(
Ты имеешь в виду при проверке ответа не вызывать функцию а просто сравнивать индекс полученного ответа с trainer.currentQuestion.correctIndex ? Можно, но в условиях задачи нужно проверять через trainer.checkAnswer(), поэтому так и оставил

2024-07-01 11:27 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +        currentQuestion = Question(
нет, сделать как сейчас, но в метод heckAnswer() не нужно передавать question, он уже есть внутри trainer

2024-07-01 11:28 UTC, danelyan requested changes

2024-07-01 11:28 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
>      fun checkAnswer(question: Question?, userAnswer: Int): Boolean {
я про то, что тут можно так `fun checkAnswer(userAnswer: Int): Boolean`

2024-07-01 12:59 UTC, danelyan approved these changes
Отлично!

2024-07-07 04:09 UTC, danelyan requested changes
Если расположить в столбик, будут влезать более длинные слова

<img width="362" alt="Screenshot 2024-07-07 at 07 09 18" src="https://github.com/4meech/LearnWordsTGBot/assets/7125622/2836a7f3-a6f7-47c5-8324-33d37b049a1d">

2024-07-07 04:09 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        val response = json.decodeFromString<Response>(responseString)
Операцию конвертирования можно делать внутри telegramBotService в методк getUpdates() и взовращать уже распарсенный response или null

2024-07-07 04:09 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        data != null && data.startsWith(CALLBACK_DATA_ANSWER_PREFIX) -> {
Можно чуть компактнее
data?.startsWith(CALLBACK_DATA_ANSWER_PREFIX) == true

2024-07-17 14:30 UTC, 4meech commented on src/main/kotlin/Telegram.kt
> +        data != null && data.startsWith(CALLBACK_DATA_ANSWER_PREFIX) -> {
![Снимок экрана 2024-07-17 172835](https://github.com/user-attachments/assets/8357485d-c8ec-45c0-a475-018814a57a3b)
с GOAWAY пока так, например... Но как именно нужно сделать я что-то всё равно не догоняю

2024-07-17 14:33 UTC, 4meech commented
![Снимок экрана 2024-07-17 172835](https://github.com/user-attachments/assets/d9edb0da-a454-41b3-a916-631c20f89bbd)
с GOAWAY пока так. Но как сделать правильно я всё равно не догоняю

2024-07-18 05:11 UTC, danelyan requested changes
С обработкой ошибок все хорошо.
Еще пара замечаний по коду.

Ну и мой комент ранее про кнопки в столбик:
<img width="400" alt="Screenshot 2024-07-18 at 08 10 16" src="https://github.com/user-attachments/assets/569de18b-133b-4992-983f-886c9357b500">

2024-07-18 05:11 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +        val sendMessage = "$URL$botToken/sendMessage"
немного сбивает при чтении, давай переменную назовем `sendMessageUrl`. Чтобы отделить от функции sendMessage

2024-07-18 05:11 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +    fun sendMessage(chatId: Long?, message: String) {
Отправка сообщений с нулябельным chatId не имеет смысла.
Куда оно отправиться в таком случае? В какой чат?
Сделай его везде ненулябельным. Ты же сам в методе `handleUpdate()` осуществляешь return если chatId == null

2024-07-18 05:11 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +            null
да, это именно то, про что я говорил

2024-07-25 08:15 UTC, 4meech commented
Вынес форматтер для reply markup в отдельный класс — показал код знакомому бородатому С++ разработчику и он напомнил мне о существовании принципов SOLID :) По логике я ж класс правильно разместил в Telegram.kt?

2024-07-27 09:12 UTC, danelyan requested changes
> Вынес форматтер для reply markup в отдельный класс — показал код знакомому бородатому С++ разработчику и он напомнил мне о существовании принципов SOLID :) По логике я ж класс правильно разместил в Telegram.kt?

Если углубиться в [SOLID](https://ru.wikipedia.org/wiki/SOLID_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)), нас тут волнует буква S (SRP) принцип единой ответственности. В таком случае, я бы разместил ReplyMarkupFormatter в файле с TelegramBotService, так как он содержит специфичную для телеграм-апи разметку кнопок

2024-07-27 09:12 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +            telegramBotService.checkNextQuestionAndSend(json = json, trainer = trainer, chatId = chatId)
давай разместим json внутри telegramBotService, чтобы не передавать каждый раз в методы `checkNextQuestionAndSend()`, `sendMenu()` и `sendMessage()`

2024-07-28 14:13 UTC, danelyan approved these changes
![yougotthis-martini](https://github.com/Gaileks/LearnEnglishWordsTelegramBot/assets/7125622/3339b61b-9b81-484f-989b-a6e73733be08)

Поздравляю! Ты сделал бота на Kotlin.

Основная часть работы пройдена. Теперь этот бот твой - можешь развивать его как хочешь. Дальше я подготовил тебе развилку из 6 простеньких доработок, все они уже в боте. Однако можешь не ограничиваться только ими, любые идеи приветствуются, просто опиши в личку и мы продумаем детали. 

Дальше как обычно - создаешь Pull Request (даже если что-то еще не работает - шлешь), а я пишу что можно улучшить.

2024-08-17 14:28 UTC, merged